### Primeiros passos no uso da biblioteca NumPy

In [3]:
#Importando o pacote
import numpy as np
#Versão do pacote
print(np.__version__)

1.20.3


In [2]:
### Exemplo I - Criando os primeiros arrays no NumPy
arr=np.array([1,2,3,4,5])
type(arr)

numpy.ndarray

In [19]:
#Exemplo II - Criando um array bidimensional
arr2=np.array([(1,4,5),(7,8,9)])
arr2

array([[1, 4, 5],
       [7, 8, 9]])

In [21]:
#Exemplo III - Criando uma matriz cheia de zeros, com dimensão especifica
arr = np.zeros((4,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [42]:
#Exemplo IV - Criando uma matriz cheia de uns, com dimensão especifica
arr=np.ones((4,7))
print(arr)
print(arr.shape) #Mostra a dimensão da matriz

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
(4, 7)


In [23]:
#Exemplo V - Criando uma matriz com uns na diagonal principal e zero no resto
arr=np.eye(8)
print(arr)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [13]:
#Gerando arrays com sequencias de dados (estilo range)
a=np.arange(0,10,0.9)
print(a)
b=np.arange(1,50,5)
print(b)

#Gerando arrays com n dados dentro de um intervalo específico
c=np.linspace(0,10,5) # 5 números entre 0 e 10, igualmente espaçados
print(c)

[0.  0.9 1.8 2.7 3.6 4.5 5.4 6.3 7.2 8.1 9.  9.9]
[ 1  6 11 16 21 26 31 36 41 46]
[]
[ 0.   2.5  5.   7.5 10. ]


In [125]:
#Ordenando arrays
a1=np.array([3,5,2,1,6,7,2,0,4,2])
print(np.sort(a1))

[0 1 2 2 2 3 4 5 6 7]


In [33]:
#Exemplo VI - Estatísticas a partir de um array(matriz)
matriz=np.array([(5,9,11),(-3,-4,7),(11,21,-10)])
print(matriz)
print(matriz.min())
print(matriz.max())
print(matriz.sum())
print(matriz.mean())
print(matriz.std())

[[  5   9  11]
 [ -3  -4   7]
 [ 11  21 -10]]
-10
21
47
5.222222222222222
8.929075823495307


In [36]:
#Operações entre matrizes e um escalar
print(matriz)
print(3*matriz)
print(2+matriz)

[[  5   9  11]
 [ -3  -4   7]
 [ 11  21 -10]]
[[ 15  27  33]
 [ -9 -12  21]
 [ 33  63 -30]]
[[ 7 11 13]
 [-1 -2  9]
 [13 23 -8]]


In [47]:
#Gerando matrizes a partir de números aleatórios
#Eh necessario importar um modulo chamado random (do proprio numpy)
from numpy import random
np.random.seed(1234)
aleat=np.random.randint(1,100,10)
print(aleat)
print(aleat/10)

[48 84 39 54 77 25 16 50 24 27]
[4.8 8.4 3.9 5.4 7.7 2.5 1.6 5.  2.4 2.7]


In [52]:
#Operações entre arrays
a=np.random.randint(1,60,6)
print(a)
b=np.random.randint(1,50,6)
print(b)
print(a+b)

[ 1 42 12 17  4  3]
[20 13  2 12 44 18]
[21 55 14 29 48 21]


In [61]:
#Operações entre arrays - A falsa mutiplicacao de matrizes
a1=np.random.randint(1,60,[3,6])
print(a1)
a2=np.random.randint(1,60,[3,6])
print(a2)
print(a1*a2)

[[51 39  9 55 18 42]
 [48 20 44 45 36 43]
 [21 27 26 44 24  3]]
[[41  2 26 28 15  5]
 [28 43  4 18 48 33]
 [56 14 57 49 42 59]]
[[2091   78  234 1540  270  210]
 [1344  860  176  810 1728 1419]
 [1176  378 1482 2156 1008  177]]


In [105]:
#A verdadeira multiplicação de matrizes
#numero de colunas da primeira matriz tem que ser igual ao numero de linhas da segunda matriz
a=np.random.randint(1,10,[3,2])
print(a)
b=np.random.randint(1,10,[2,3])
print(b)
#Multiplicacao das matrizes a e b (o resultado sera o nuimero de linhas de a vs o numero de colunas de b)
a.dot(b)

[[3 4]
 [5 3]
 [2 5]]
[[1 1 3]
 [2 3 6]]


array([[11, 15, 33],
       [11, 14, 33],
       [12, 17, 36]])

In [107]:
#Transposição de arrays
print(b)
print(b.shape) #Tamanho da matriz
print(b.T) #Transposição da matriz

[[1 1 3]
 [2 3 6]]
(2, 3)
[[1 2]
 [1 3]
 [3 6]]


In [123]:
#Determinante da matriz
A=np.random.randint(1,10,[4,4])
print(A)
#Determinante da matriz
print('O Determinante da matriz A é :', np.linalg.det(A)) #Muitas funções de álgebra linear estão no módulo linalg do NumPy
#Inversa da matriz A
print('A Inversa da matriz A é :', np.linalg.inv(A)) 

[[4 9 8 6]
 [2 4 2 4]
 [1 3 1 4]
 [6 3 7 7]]
O Determinante da matriz A é : 111.99999999999996
A Inversa da matriz A é : [[-0.26785714  1.36607143 -1.08928571  0.07142857]
 [ 0.03571429  0.51785714 -0.32142857 -0.14285714]
 [ 0.23214286 -0.88392857  0.41071429  0.07142857]
 [-0.01785714 -0.50892857  0.66071429  0.07142857]]


In [120]:
#Comparação entre arrays (elemento a elemento)
a=np.array([1,4,7,10])
b=np.array([2,1,5,11])
print(a==b)
print(a!=b)
print(a>b)
print(a<b)

#Comparação entre arrays (array inteiro)
print(np.array_equal(a,b))
c=np.array([5,3])
d=np.array([5,3])
print(np.array_equal(c,d))

[False False False False]
[ True  True  True  True]
[False  True  True False]
[ True False False  True]
False
True


In [86]:
#Algumas funções matemáticas presentes
print(np.sum(a)) #Soma dos elementos do array
print(np.mean(a)) #Média dos elementos do array
print(np.std(a)) #Desvio padrão dos elementos do array

22
5.5
3.3541019662496847


In [8]:
a=np.array([(3,4, 5),(5, 6, 4),(5, 3, 2)])
a.shape

(3, 3)