In [1]:
# Importando o pacote numpy

import numpy as np

In [2]:
# Verificando a versão do numpy

print(np.__version__)

1.21.3


In [3]:
# Exemplo 1 - Criando os primeiros arrays no numpy

arr = np.array([1, 2, 3, 4, 5])
type(arr)

numpy.ndarray

In [6]:
# Exemplo 2 - Criando um array bidimensional

arr2 = np.array([(1, 4, 5), (7, 8, 9)])
arr2

array([[1, 4, 5],
       [7, 8, 9]])

In [10]:
# Exemplo 3 - Criando uma matriz cheia de zeros, com dimensão especifica

arr = np.zeros((4,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
# Exemplo 4 - Criando uma matriz cheia de uns, com dimensão especifica

arr = np.ones((4,7))
print(arr)
print(arr.shape)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
(4, 7)


In [12]:
# Exemplo 5 - Criando uma matriz com uns na diagonal principal e zero no resto

arr = np.eye(8)
print(arr)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [13]:
# Gerando arrays com sequencias de dados (estilo range)

a = np.arange(0, 10, 0.9)
print(a)
b = np.arange(1, 50, 5)
print(b)

[0.  0.9 1.8 2.7 3.6 4.5 5.4 6.3 7.2 8.1 9.  9.9]
[ 1  6 11 16 21 26 31 36 41 46]


In [14]:
# Gerando  arrays com n dados dentro de um intervalo especifico

c = np.linspace(0, 10, 5)  # 5 numeros entre o e 10, igualmente espaçados
print(c)

[ 0.   2.5  5.   7.5 10. ]


In [17]:
# ordenamento de arrays

a1 = np.array([3, 5, 2, 1, 6, 7, 2, 0, 4, 2])
print(np.sort(a1))
print()

a2 = np.array([(5, 9, 11), (-3, -4, 7), (11, 21, -10)])
print(np.sort(a2))



[0 1 2 2 2 3 4 5 6 7]

[[  5   9  11]
 [ -4  -3   7]
 [-10  11  21]]


In [18]:
# Exemplo 6 - Estatistícas a partir de um array(matriz)

matriz = np.array([(5, 9, 11), (-3, -4, 7), (11, 21, -10)])
print(matriz)
print(matriz.min())
print(matriz.max())
print(matriz.sum())
print(matriz.mean())
print(matriz.std())

[[  5   9  11]
 [ -3  -4   7]
 [ 11  21 -10]]
-10
21
47
5.222222222222222
8.929075823495307


In [20]:
# Operações entre matrizes e um escalar

print(matriz)
print(3*matriz)
print(2+matriz)

[[  5   9  11]
 [ -3  -4   7]
 [ 11  21 -10]]
[[ 15  27  33]
 [ -9 -12  21]
 [ 33  63 -30]]
[[ 7 11 13]
 [-1 -2  9]
 [13 23 -8]]


In [21]:
# Gerando matrizes a partir de números aleatórios
# Eh necessário importar um módulo chamado random (do próprio numpy)
from numpy import random
np.random.seed(1234)
aleat = np.random.randint(1, 100, 10)
print(aleat)
print(aleat / 10)

[48 84 39 54 77 25 16 50 24 27]
[4.8 8.4 3.9 5.4 7.7 2.5 1.6 5.  2.4 2.7]


In [30]:
# A função numpy.random.seed() é usada para definir a semente para o algoritmo gerador de números pseudo-aleatórios
#  em Python. O algoritmo gerador de número pseudo-aleatório executa algumas operações predefinidas na semente e produz
#  um número pseudo-aleatório na saída. A semente atua como um ponto de partida para o algoritmo. Um número
#  pseudo-aleatório é um número que parece aleatório, mas na verdade não é. Na verdade, os computadores são incapazes de
#  gerar um número verdadeiramente aleatório porque os computadores são determinísticos e seguem consistentemente um
#  determinado conjunto de instruções. A ideia por trás disso é que sempre obteremos o mesmo conjunto de números
#  aleatórios para a mesma semente em qualquer máquina.

np.random.seed(1234)
aleat1 = np.random.randint(1, 100, 10)
print(aleat1)
print()


np.random.seed(1)
array = np.random.rand(5)
np.random.seed(1)
array2 = np.random.rand(5)
print(array)
print(array2)

[48 84 39 54 77 25 16 50 24 27]

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01
 1.46755891e-01]


In [31]:
# Operações entre arrays

a = np.random.randint(1, 60, 6)
print(a)
b = np.random.randint(1, 50, 6)
print(b)
print(a+b)

[17  2 13  8 46  7]
[26 21 38 19 21 12]
[43 23 51 27 67 19]


In [33]:
# Operações entre arrays - A falsa multiplicacao de matrizes
# Atenção para o falso processo de multiplicação de matrizes. Perceba que o que ocorre é uma simples multiplicação de
#  números entre os elementos das respectivas posições das matrizes a1 e a2.

a1 = np.random.randint(1, 60, [3, 6])
print(a1)
a2 = np.random.randint(1, 60, [3, 6])
print(a2)
print(a1 * a2)

[[50 58  4  5 25 50]
 [44 13 27 53 17 46]
 [52 42 19 16  1  5]]
[[26 48 35 24  8 27]
 [26 41 23 10  4 40]
 [24 37 28 38 58 20]]
[[1300 2784  140  120  200 1350]
 [1144  533  621  530   68 1840]
 [1248 1554  532  608   58  100]]


In [34]:
# A verdadeira multiplicação de matrizes
# Número de colunas da primeira matriz tem que ser igual ao número de linhas da segunda matriz

a = np.random.randint(1, 10, [3, 2])
print(a)
b = np.random.randint(1, 10, [2, 3])
print(b)

# Multiplicação das matrizes a e b ( o resultado sera o numero de linhas de a vezes o numero de colunas de b)
a.dot(b)

[[7 9]
 [1 3]
 [8 8]]
[[8 4 1]
 [9 8 8]]


array([[137, 100,  79],
       [ 35,  28,  25],
       [136,  96,  72]])

In [35]:
# Transposição de array

print(b)
print(b.shape) # Tamanho da matriz
print(b.T)     # Transposição da matriz

[[8 4 1]
 [9 8 8]]
(2, 3)
[[8 9]
 [4 8]
 [1 8]]


In [36]:
# Comparação entre arrays (elemento a elemento)

a = np.array([1, 4, 7, 10])
b = np.array([2, 1, 5, 11])
print(a == b)
print(a != b)
print(a > b)
print(a < b)

[False False False False]
[ True  True  True  True]
[False  True  True False]
[ True False False  True]


In [37]:
# Comparação entre array (array inteiro)

print(np.array_equal(a, b))
c = np.array([5, 3])
d = np.array([5, 3])
print(np.array_equal(c, d))

False
True


In [38]:
# Determinante da matriz
A = np.random.randint(1, 10, [4, 4])
print(A)
# Determinante da matriz
print('O determinante da matriz A é :', np.linalg.det(A)) # Muitas funções de algebra linear estão no modulo linalg do NumPy
# Inversa da matriz A
print('A inversa da matriz A é :', np.linalg.inv(A))

[[2 2 4 1]
 [9 7 5 6]
 [7 3 6 8]
 [9 5 5 8]]
O determinante da matriz A é : 42.00000000000004
A inversa da matriz A é : [[ 1.0952381  -1.54761905 -1.76190476  2.78571429]
 [-0.9047619   1.45238095  1.23809524 -2.21428571]
 [ 0.38095238 -0.19047619 -0.04761905  0.14285714]
 [-0.9047619   0.95238095  1.23809524 -1.71428571]]


In [39]:
# Algumas funções matematicas presentes

print(np.sum(a))    # Soma dos elemetos do array
print(np.mean(a))   # Média dos elementos do array
print(np.std(a))    # Desvio padrão dos elementos do array

22
5.5
3.3541019662496847
