# 8ª Sessão “Mão na Massa” (tempo: 15 minutos)

## Realize as seguintes atividades usando um notebook Jupyter
### a) Explore um pouco o módulo “math”. Que funções ou constantes podem ser interessantes?
### b) Crie um array com a seguinte característica: [[3 4 5] [5 6 4] [5 3 2]]. Calcule a dimensão dessa matriz. Qual o determinante e a inversa dessa matriz? Extraia estatísticas descritivas dessa matriz (mínimo, média, máximo e desvio padrão).
### c) Gere 2 matrizes com numeros inteiros aleatórios e promova a multiplicação entre elas. Houve algum erro? Qual a condição para que seja possível a multiplicação de 2 matrizes? Qual deve ser o formato da matriz resultante?
### d) Gere um array que seja uma sequência de números de 0 a 10, com razão de 1.2.
### e) Gere um array que seja uma sequência de números de 100 a 10, com razão de -15.
### f) Gere uma matriz de 6x6, sendo cada linha uma sugestão aleatória de dezenas para um jogo da megasena.

### a) Explore um pouco o módulo “math”. Que funções ou constantes podem ser interessantes?

In [2]:
# math - Este módulo fornece acesso às funções matemáticas. Segue exemplos de algumas funções matemáticas

import math

# math.ceil(x) - Return the ceiling of x, the smallest integer greater than or equal to x.
a = 3.0
print(math.ceil(a))

# math.comb(n, k) - Retorna o número de maneiras de escolher k itens de n itens sem repetição e sem ordem.
# Avalia para n! / (k! * (n - k)!) quando k <= n e avalia para zero quando k > n.
print(math.comb(5, 2))

# math.factorial(x) - Retorna x fatorial como um inteiro. Levanta ValueError se x não for integral ou for negativo.
print(math.factorial(5))

# math.pow(x, y) - Retorna x elevado à potência y.
print(math.pow(2,3))

# math.sqrt(x) - Retorna a raiz quadrada de x.
print(math.sqrt(81))

3
10
120
8.0
9.0


### b) Crie um array com a seguinte característica: [[3 4 5] [5 6 4] [5 3 2]]. Calcule a dimensão dessa matriz.  Qual o determinante e a inversa dessa matriz? Extraia estatísticas descritivas dessa matriz (mínimo, média, máximo e desvio padrão).

In [3]:
# importe o modulo numpy

import numpy as np

In [4]:
# Definição da matriz
arr = np.array([(3, 4, 5), (5, 6, 4), (5, 3, 2)])
print(arr)

# Dimensão
print("A dimensão da matriz é:", arr.shape)

# Determinante
print("O determinante da matriz é:", np.linalg.det(arr))

# Inversa
print("A inversa da matriz é:", np.linalg.inv(arr))

# Extraia estatísticas descritivas dessa matriz (mínimo, média, máximo e desvio padrão)
print("O menor elemento (minimo) da matriz é:", np.min(arr))
print("O media dos elementos da matriz é:", np.mean(arr))
print("O maior elemento (maximo) da matriz é:", np.max(arr))
print("O desvio padrão da matriz é:", np.std(arr))

[[3 4 5]
 [5 6 4]
 [5 3 2]]
A dimensão da matriz é: (3, 3)
O determinante da matriz é: -35.00000000000001
A inversa da matriz é: [[ 0.         -0.2         0.4       ]
 [-0.28571429  0.54285714 -0.37142857]
 [ 0.42857143 -0.31428571  0.05714286]]
O menor elemento (minimo) da matriz é: 2
O media dos elementos da matriz é: 4.111111111111111
O maior elemento (maximo) da matriz é: 6
O desvio padrão da matriz é: 1.1967032904743342


### c) Gere 2 matrizes com numeros inteiros aleatórios e promova a multiplicação entre elas. Houve algum erro? Qual a condição para que seja possível a multiplicação de 2 matrizes? Qual deve ser o formato da matriz resultante?

In [5]:
# Para multiplicar matrizes, o número de colunas da primeira matriz
# tem que ser igual ao número de linhas da segunda matriz.

a = np.random.randint(1, 10, [2, 3])
print(a)
b = np.random.randint(1, 10, [3, 2])
print(b)

# Multiplicação das matrizes a e b ( o resultado sera o numero de linhas de a vezes o numero de colunas de b)
a.dot(b)


[[4 7 9]
 [6 1 9]]
[[7 5]
 [2 5]
 [3 5]]


array([[ 69, 100],
       [ 71,  80]])

### d) Gere um array que seja uma sequência de números de 0 a 10, com razão de 1.2.

In [6]:
a = np.arange(0, 10, 1.2)
print(a)

[0.  1.2 2.4 3.6 4.8 6.  7.2 8.4 9.6]


### e) Gere um array que seja uma sequência de números de 100 a 10, com razão de -15.

In [7]:
a = np.arange(100, 10, -15)
print(a)

[100  85  70  55  40  25]


### f) Gere uma matriz de 6x6, sendo cada linha uma sugestão aleatória de dezenas para um jogo da megasena.

In [9]:
a = np.random.randint(1,61, [6, 6])
print(a)

[[46 19 51 51 23 51]
 [54 52 32 46 13  3]
 [26 52  4 25 15  6]
 [15 29 44 33 35 35]
 [30 29 36 31  8 41]
 [50 12  9 25  7  6]]


In [12]:
x = 1
while x < 7:
    a = np.arange(1, 61)
    np.random.shuffle(a)
    np.sort(a[:6])
    print(np.sort(a[:6]))
    x += 1

[ 1  6 24 25 31 38]
[21 30 50 54 56 58]
[ 2 15 39 44 48 59]
[21 38 39 41 47 55]
[ 3  6  7 46 47 55]
[18 19 23 24 46 52]


In [10]:
# Shuffle a list (reorganize the order of the list items)

import random

mylist = ["apple", "banana", "cherry"]
random.shuffle(mylist)

print(mylist)

['banana', 'apple', 'cherry']


In [13]:
l = list(range(5))
print(l)
# [0, 1, 2, 3, 4]

random.shuffle(l)
print(l)
# [1, 0, 4, 3, 2]

[0, 1, 2, 3, 4]
[1, 0, 3, 2, 4]


In [15]:
# l = list(range(5))
# print(l)
l = [0, 1, 2, 3, 4, 4]

random.shuffle(l)
print(l)
# [1, 0, 4, 3, 2]

[0, 4, 4, 3, 1, 2]


In [18]:
a = np.arange(1,61)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60])

In [20]:
np.random.shuffle(a)
a

array([50, 57,  8, 10, 12, 26, 48,  5, 31, 52, 36, 35, 32, 20, 18, 45, 16,
       38, 25, 44, 54, 17, 34, 42, 51,  3,  9, 14, 22, 24, 49, 27, 30, 41,
       11, 47, 55, 59,  4, 53, 23,  7, 19, 46, 56, 29, 21, 13, 37, 58,  6,
       15,  1,  2, 43, 60, 40, 39, 33, 28])

In [21]:
np.sort(a[:6])
print(np.sort(a[:6]))

[ 8 10 12 26 50 57]
